
SELECT
s.ORGANIZATION as Organismo,
c.FIRSTNAME as NOMBRE,
c.LASTNAME as APELLIDO,
c.ID_NUMBER as Cedula,
s.ORDER_CONTACT_NUMBER as COD_CONTACTO,
c.BIRTHDATE as FECHA_DE_NACIMIENTO,
TO_CHAR(c.BIRTHDATE, 'YYYY-MM-DD') as FECHA_DE_NACIMIENTO,
TO_CHAR(s.REFERENCE_DATE, 'YYYY-MM-DD') as Fecha_Compra,
TO_CHAR(s.PRODUCT_DATE_TIME, 'YYYY-MM-DD')  as Fecha_evento,
CASE 
    WHEN c.BIRTHDATE IS NULL THEN NULL
    ELSE FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12)
END AS Edad,
CASE 
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) IS NULL THEN 'SIN DATO'
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) < 18 THEN 'Menor de 18'
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) <= 24 THEN '18 a 24'
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) <= 34 THEN '25 a 34'
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) <= 44 THEN '35 a 44'
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) <= 54 THEN '45 a 54'
    WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, c.BIRTHDATE) / 12) <= 64 THEN '55 a 64'
    ELSE 'Mayor a 64'
END AS Rango_de_edad,
c.EMAIL as CORREO,
c.NAT_NUMBER_CELLPHONE as MoVIL,
CASE 
    WHEN c.GENDER = 'MALE' THEN 'HOMBRE'
    WHEN c.GENDER = 'FEMALE' THEN 'MUJER'
    WHEN c.GENDER = 'UNKNOWN' AND c.ADDRESS_SALUTATION IN ('Mr', 'Señor', 'Señor,', 'Don') THEN 'HOMBRE'
    WHEN c.GENDER = 'UNKNOWN' AND c.ADDRESS_SALUTATION IN ('Ms','Mrs', 'Miss', 'Señora', 'Señorita') THEN 'MUJER'
    WHEN c.GENDER = '' AND c.ADDRESS_SALUTATION IN ('Mr', 'Señor', 'Señor,', 'Don') THEN 'HOMBRE'
    WHEN c.GENDER = '' AND c.ADDRESS_SALUTATION IN ('Ms','Mrs', 'Miss', 'Señora', 'Señorita') THEN 'MUJER'
    WHEN COALESCE(c.GENDER, '') = '' AND c.ADDRESS_SALUTATION IN ('Mr', 'Señor', 'Señor,', 'Don') THEN 'HOMBRE'
    WHEN COALESCE(c.GENDER, '') = '' AND c.ADDRESS_SALUTATION IN ('Ms','Mrs', 'Miss', 'Señora', 'Señorita') THEN 'MUJER'
     WHEN c.GENDER IS NULL AND c.ADDRESS_SALUTATION IN ('Mr', 'Señor', 'Señor,', 'Don') THEN 'HOMBRE'
    WHEN c.GENDER IS NULL AND c.ADDRESS_SALUTATION IN ('Ms','Mrs', 'Miss', 'Señora', 'Señorita') THEN 'MUJER'
    ELSE 'SIN DATO'
END AS Genero,
c.MAIN_ADDR_LINE1 as Direccion, 
c.MAIN_ADDR_TOWN as Ciudad_del_cliente,
c.MAIN_ADDR_GEO_ZONE as Departamento_del_cliente,
c.MAIN_ADDR_COUNTRY as Pais_del_cliente,
s.SALES_CHANNEL_TYPE as Canal_de_venta,
s.PRODUCT as Evento,
s.PROMOTION as Promocion,
s.LOGICAL_SEAT_CATEGORY as Categoria_Logica,
s.T_SITE_ID as Codigo_del_venue,
s.SITE as Venue,
SUM(s.NET_SOLD_T_QTY)- SUM(s.NET_SOLD_C_QTY) as Tickets_comprados,
SUM(s.NET_SOLD_C_QTY) AS Cortesias,
SUM(s.NET_SOLD_TKT_AMT_ITX) AS Recaudo

 

--CASE
--    WHEN tabla_metodos.GRUPO = '' THEN 'Cortesia'
--    WHEN COALESCE(tabla_metodos.GRUPO, '') = ''  THEN 'Cortesia'
--    WHEN tabla_metodos.GRUPO IS NULL THEN 'Cortesia'
--ELSE tabla_metodos.GRUPO 
--END as Metodo_de_pago,

FROM
D_SALES_LIST_SALES_V1_0 s
JOIN D_CONTACT_LIST_V1_0 c ON s.T_ORDER_CONTACT_ID = c.T_CONTACT_ID
    --LEFT JOIN (SELECT * FROM (SELECT FILE_NUMBER, PAYMENT_METHOD, ROW_NUMBER() OVER (PARTITION BY FILE_NUMBER ORDER BY PAYMENT_METHOD) AS row_num
    --FROM D_SALES_PROD_PAYMENT_V1_0) WHERE row_num = 1) tabla_pago ON s.FILE_NUMBER = tabla_pago.FILE_NUMBER)

 

   -- LEFT JOIN MAESTRO_METODOS tabla_metodos ON tabla_pago.PAYMENT_METHOD = tabla_metodos.PAYMENT_METHOD

WHERE s.ORGANIZATION in ('Idartes')
	  --AND s.ORDER_CONTACT_NUMBER IN ('6258518','6987851')
 

GROUP BY
s.ORGANIZATION,c.FIRSTNAME,c.LASTNAME,c.ID_NUMBER,s.ORDER_CONTACT_NUMBER,c.BIRTHDATE,s.REFERENCE_DATE,s.PRODUCT_DATE_TIME,
c.EMAIL,c.NAT_NUMBER_CELLPHONE,c.GENDER,c.ADDRESS_SALUTATION,c.MAIN_ADDR_LINE1,c.MAIN_ADDR_TOWN,c.MAIN_ADDR_GEO_ZONE,c.MAIN_ADDR_COUNTRY, 
s.SALES_CHANNEL_TYPE,s.PRODUCT,s.PROMOTION,s.LOGICAL_SEAT_CATEGORY,s.T_SITE_ID,s.SITE